---
- name: restart squid
  service:
    name: squid.service
    state: restarted

- name: reload squid
  service:
    name: squid.service
    state: reloaded

- name: restart squid-cron
  service:
    name: squid-cron.service
    state: restarted
