---
- name: install container files
  copy:
    src: squid
    dest: /service
    mode: preserve
  notify: reload squid

- name: build squid image
  containers.podman.podman_image:
    state: build
    force: true
    name: squid
    path: /service/squid
  notify: restart squid

- name: ensure log directory exists
  file:
    path: /var/log/squid
    state: directory

- name: enable nonlocalbind
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    state: present
    sysctl_set: true

- name: install squid systemd unit
  template:
    src: squid.service
    dest: /etc/systemd/system/squid.service
  notify:
    - reload systemd
    - restart squid

- name: install squid-cron systemd unit
  copy:
    src: squid-cron.service
    dest: /etc/systemd/system/squid-cron.service
  notify:
    - reload systemd
    - restart squid-cron

- name: activate squid services
  service:
    name: '{{ item }}'
    state: started
    enabled: true
  loop:
    - squid
    - squid-cron
