---
- name: copy image files
  copy:
    src: darkhttpd
    dest: /service

- name: build darkhttpd image
  containers.podman.podman_image:
    state: build
    force: true
    name: darkhttpd
    path: /service/darkhttpd
